---
# handlers file for install_docker

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    group: docker

- name: Enable Docker and startup
  service:
    name: docker
    state: started
    enabled: yes