---
all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: 22
    ansible_connection: ssh
    ansible_python_interpreter: /usr/bin/python3
    docker_compose_version: v2.2.3


project:
  hosts:
    develop:
      ansible_host: 18.198.218.11
      ansible_user: ubuntu
      # docker_subnet: 172.177.0.0/16
      # prod

    stage:
      ansible_host: 54.202.55.173
      ansible_user: ubuntu
      # dev
    
    main:
      ansible_host:
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python2

